export const DELETE_ROW_ACTION = "DELETE_ROW_ACTION";

export const EDITED_ROW_ACTION = "EDITED_ROW_ACTION";

export const ADD_NEW_DATA_ACTION = "ADD_NEW_DATA_ACTION";

export const IS_REGISTERED_ACTION = "IS_REGISTERED_ACTION";
